<?php 
    $this->Html->LoadCss('area-admin');
    $msg = "Nesta opção você pode escolher em qual album de fotos você deseja postar";
    $temp['Tenap']         = "blog/imagem/show/tenap";
    $temp['Inexperientes'] = "blog/imagem/show/inexperientes";
?>
<div class="painel-item">
    <div class="painel-item-titulo">
        <h2>Selecione o Álbum</h2>
        <span class="painel-item-desc"><?php echo $msg; ?></span>
    </div>

    <div class="painel-item-conteudo">
        <?php
        foreach($temp as $name => $item){ ?>
           <div class="link"><a href="<?php echo $this->Html->getLink($item); ?>"><?php echo ucfirst($name); ?></a></div>
        <?php }?>
    </div>
</div>