<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:06:03.
 */
class blog_imagemModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var blog_imagemModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new blog_imagemModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers blog_imagemModel::getFotos
     * @todo   Implement testGetFotos().
     */
    public function testGetFotos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers blog_imagemModel::getDestaques
     * @todo   Implement testGetDestaques().
     */
    public function testGetDestaques() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
